name: Close stale issues and PRs

on:
  schedule:
    - cron: "30 1 * * *"   # Runs daily at 1:30am UTC, because you have better things to do while you sleep
  workflow_dispatch:        # Run it manually if you feel like playing God with your issues
  issue_comment:
    types: [created]        # Wake up the workflow when someone comments (because hope springs eternal)

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Make sure the labels exist, so the action doesn’t cry about it
      - name: Ensure labels exist
        run: |
          gh label create "Awaiting Response" --color "#FFA500" --description "Waiting for user response" || echo "Label exists"
          gh label create "not-stale" --color "#00FF00" --description "Exempt from stale" || echo "Label exists"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Actually run the stale action, like a responsible repo owner
      - name: Mark stale issues and PRs
        uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open 10 days with no activity. Remove stale label or comment, or this will be closed in 7 days. Don’t make me come back here."
          stale-pr-message: "This PR is stale because it has been open 3 days with no activity. Remove stale label or comment, or this will be closed in 27 days. Chop chop."
          close-issue-message: "This issue was closed because it was stale for 17 days with no activity. That’s longer than some people’s attention spans."
          close-pr-message: "This PR was closed because it was stale for 30 days with no activity. RIP."
          days-before-issue-stale: 10
          days-before-pr-stale: 3
          days-before-issue-close: 17
          days-before-pr-close: 30
          exempt-pr-labels: not-stale
          exempt-issue-labels: not-stale
          stale-pr-label: "Awaiting Response"
